---
apiVersion: v1
kind: Pod
metadata:
  name: cm-volume-demo
spec:
  containers:
    - image: alpine
      name: alpine-cont
      args:
        - /bin/sh
        - -c
        - sleep 1d
      env:
        - name: UI_PROP_FILENAME
          valueFrom:
            configMapKeyRef:
              name: cm-demo
              key: "ui.properties.filename"
      volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
  volumes:
    - name: config
      configMap:
        name: cm-demo