FROM openjdk:8-jre-slim
ADD https://referenceappkhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar /spring-petclinic.jar
EXPOSE 8080
CMD ["java",  "-jar",  "/spring-petclinic.jar"]